[package]
name = "rpi-futures"
version = "0.1.0"
authors = ["Dave Townsend <dtownsend@oxymoronical.com>"]
edition = "2018"

[dependencies]
rppal = "^0.11.3"
futures-preview = "=0.3.0-alpha.18"
log = "^0.4.8"
